name: YouTube Screenshot

on:
 workflow_dispatch

jobs:
  capture_screenshots:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        usersname:
          - "herst277"
          - "kimnguyennanh"
        
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - run: pip install ffmpeg-python

      - name: Create user folders
        run: mkdir -p $GITHUB_WORKSPACE/${{ matrix.usersname }}

      - name: Run Selenium script
        run: python main.py -user ${{ matrix.usersname }}  -output ${{ matrix.usersname }} 

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.usersname }}
          path: ${{ matrix.usersname }}
