name: YT

on:
 workflow_dispatch

jobs:
  capture_screenshots:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        usersname:
          - "park.77m1"
          - "buiquoc_sw"
          - "honguynvn04"
          - "365.ngy.nh.em"
          - "duongkimochii"
          - "hmatuan9"
          - "hpp358965"
          - "bimostreetworkout.id"
          - "huutinh103"
          - "herst277"
          - "trinhatquankhu1"
          - "kenvo12022001"
          - "rforrachman"
          - "ntf_205"
          - "ngthanhlong021006"
          - "dng.m.prayer"
          - "tuntl675"
          - "truongminhdung1904"
          - "ngthanhlong021006"
          - "voquyhuyyy24102001"
          - "hy.calis"
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg
        run: sudo apt-get install ffmpeg

      - name: Create user folders
        run: mkdir -p $GITHUB_WORKSPACE/${{ matrix.usersname }}


      - name: Run Selenium script
        run: python main.py -user ${{ matrix.usersname }} -mode automatic -output ${{ matrix.usersname }} -ffmpeg 

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.usersname }}
          path: ${{ matrix.usersname }}
