name: YT

on:
 workflow_dispatch

jobs:
  capture_screenshots:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        usersname:
          # - "park.77m1"
         # - "bonbarber2210"
          - "minhly06_01"
         # - "hunggymcalis"
          #- "quocvu93"
          - "buiquoc_sw"
          - "truongminhdung1904"
         # - "anhhhh_tu"
         # - "hongduong.1199"
          - "honguynvn04"
          - "365.ngy.nh.em"
          - "duongkimochii"
          - "duongtapxo"
          - "hmatuan9"
          - "hpp358965"
          - "bimostreetworkout.id"
          - "huutinh103"
          - "herst277"
          - "anhbodoi6mui"
          #- "trinhatquankhu1"
          #- "kenvo12022001"
          - "hy.calis"
          - "rforrachman"
          - "ntf_205"
          - "ngthanhlong021006"
          - "hoanganh1112022"
          - "tuntl675"
          - "chulongcuaemm"
          - "141201nth"
          #- "viluong.gg"
      
          # #- "voquyhuyyy24102001"
          - "congmanhfitness"
          - "yeuem2003n"
          - "rhenz_win"
          - "ikram_rmdn"
          - "minhnam2004"
          #- "tuangym98"
          - "thanabodxx"
          - "thang_masic"
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg
        run: sudo apt-get install ffmpeg

      - name: Create user folders
        run: mkdir -p $GITHUB_WORKSPACE/${{ matrix.usersname }}


      - name: Run Selenium script
        run: python main.py -user ${{ matrix.usersname }} -mode automatic -output ${{ matrix.usersname }} -ffmpeg 

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.usersname }}
          path: ${{ matrix.usersname }}
